version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root_password  # Reads from mounted file
      MYSQL_DATABASE: bunbit_computerai_database
      MYSQL_USER_FILE: /run/secrets/db_user  # Optional: for user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password  # Reads from mounted file
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    secrets:  # Grant access to these secrets
      - root_password
      - db_password
      - db_user
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$(cat /run/secrets/root_password)"]
      interval: 10s
      retries: 5
      timeout: 5s

secrets:  # Define the secrets from local files
  root_password:
    file: ./secrets/root_password.txt
  db_password:
    file: ./secrets/db_password.txt
  db_user:
    file: ./secrets/db_user.txt

volumes:
  mysql_data: