plugins {
    id 'java'
    id 'org.teavm' version '0.14.1'
}

group 'com.bunbit'
version '0.1.0'

sourceCompatibility = '17'
targetCompatibility = '17'

repositories {
    mavenCentral()
}

dependencies {
    implementation teavm.libs.jso
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.3'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.3'
}

test {
    useJUnitPlatform()
}

teavm {
    all {
        mainClass = 'com.bunbit.render.RenderHelpers'
        outputDir = file('../../wasm/generated')
    }

    wasmGC {
        targetFileName = 'bunbit-renderhelpers.wasm'
        copyRuntime = true
        obfuscated = false
        debugInformation = true
    }
}

tasks.assemble.dependsOn(tasks.buildWasmGC)
